apiVersion: v1
kind: Pod
metadata:
  name: kafka-costumer-2
  labels:
    app: kafka-costumer-2
spec:
  containers:
    - name: costumer-2
      image: ervincaravaliibarra/kafka-costumer-2:latest
      env:
        - name: KAFKA_BROKER
          value: kafka-broker-1:9092