apiVersion: v1
kind: Pod
metadata:
  name: kafka-costumer
  labels:
    app: kafka-costumer
spec:
  containers:
    - name: costumer
      image: ervincaravaliibarra/kafka-costumer:latest
      env:
        - name: KAFKA_BROKER
          value: kafka-broker-1:9092
