apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer-2
  labels:
    app: kafka-producer-2
spec:
  containers:
    - name: producer-2
      image: ervincaravaliibarra/kafka-producer-2:latest
      env:
        - name: KAFKA_BROKER
          value: kafka-broker-1:9092